<class 'sqlalchemy.orm.exc.UnmappedInstanceError'>: Class 'sqlalchemy.ext.declarative.api.DeclarativeMeta' is not mapped; was a class (data.users.User) supplied where an instance was required?
2020-03-22 16:14:35.934822
-----
<class 'sqlalchemy.orm.exc.UnmappedInstanceError'>Class 'sqlalchemy.ext.declarative.api.DeclarativeMeta' is not mapped; was a class (data.users.User) supplied where an instance was required?
2020-03-22 16:34:10.411305
-----
<class 'sqlalchemy.orm.exc.UnmappedInstanceError'>: Class 'sqlalchemy.ext.declarative.api.DeclarativeMeta' is not mapped; was a class (data.users.User) supplied where an instance was required?
2020-03-22 16:40:00.800138
-----
<class 'sqlalchemy.orm.exc.UnmappedInstanceError'>: Class 'sqlalchemy.ext.declarative.api.DeclarativeMeta' is not mapped; was a class (data.users.User) supplied where an instance was required?
2020-03-22 16:45:46.847682
-----
<class 'sqlalchemy.exc.IntegrityError'>: (sqlite3.IntegrityError) UNIQUE constraint failed: users.email
[SQL: INSERT INTO users (surname, name, age, position, speciality, address, email, hashed_password, modified_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Vo', 'Il', 16, 'p', 's', 'b', 'xcvxcv@gmail.com', 'pbkdf2:sha256:150000$vYcPNqzD$d59790459b4cb0b8f930b98f7108bbc8e605a1537817f62cce46151f08554735', '2020-03-22 17:20:52.257561')]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-03-22 17:20:52.260070
-----
